"""
Django settings for configuracion project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import environ
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

env = environ.Env()
environ.Env.read_env()


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)z9tn+c_iz!mx)b3+^(+!2ah9n&_jg%-@t%%)&x$i-33g)f2x3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Segmentacion o division del proyecto

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

PROJECT_APPS = [
    'apps.cart',
]

THIRD_PARTY_APPS = [
    'corsheaders',
    'rest_framework',
    'rest_framework_api',
    'rest_framework_simplejwt', 
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework.authtoken',
    'drf_spectacular', #django spectacular sirve como documentacion de swagger
    'pwa'
]


INSTALLED_APPS = DJANGO_APPS + PROJECT_APPS + THIRD_PARTY_APPS


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Debe ir antes de cualquier middleware que maneje solicitudes
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'configuracion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'configuracion.wsgi.application'
ASGI_APPLICATION = 'configuracion.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


#Con Docker y con Postgres
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DB_NAME', 'carrito'),  
        'USER': os.environ.get('DB_USER', 'jesus'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'Jesus1'),
        'HOST':  os.environ.get('DB_HOST', 'db_carrito'),  # Conexion con el docker-compose.yaml
        'PORT': '5432',
        'ATOMIC_REQUESTS': True,  
    }
}

#Sin Docker/SQLITE3
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}



CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6381/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


#Codigo para definir el formato de numeros. Ejemplo 100.000,00 (formato europeo/latinoamericano) o 100,000.00 (formato anglosajón),
USE_L10N = True  # Asegúrate que esté en True
USE_THOUSAND_SEPARATOR = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Define la ruta para MEDIA_ROOT

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # Define la ruta para STATIC_ROOT


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'build/static'),
]
FILE_UPLOAD_PERMISSIONS = 0o640

EMAIL_BACKEND = 'django.core.mail.backend.console.EmailBackend'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


##Modificado por mi 

CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {

    #DRF JWT
       'DEFAULT_AUTHENTICATION_CLASSES': (
           'rest_framework_simplejwt.authentication.JWTAuthentication',
       ),

    #PERMISOS
       'DEFAULT_PERMISSION_CLASS': (
           'rest_framework.permissions.IsAuthenticatedOrReadOnly',
        ),
    #DRF SPECTACULAR
       'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
  
   }

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

SIMPLE_JWT = {
    #'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('JWT',),
    #'USER_ID_FIELD': 'id',
    #'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    
    #'TOKEN_TYPE_CLAIM': 'token_type',
    #'JTI_CLAIM': 'jti',
    #'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    
    #Tiempo de expiracion del TOKEN

    #PARA DESARROLLO ESTA CONFIGURACION

    # Tiempo de vida del token de acceso (default: 5 minutos)
    #'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # 1 hora
    ## Tiempo de vida del token de refresco (default: 1 día)
    #'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # 1 semana

    #PARA PRODUCCION ESTA CONFIGURACION
    #'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365*100),  # 100 años (prácticamente nunca)

    #'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365*100),  # 100 años (prácticamente nunca)
    # Tiempo de vida del token de refresco cuando se usa para renovar (default: None)

    # Permite renovar el refresh token cada vez que se usa
    'ROTATE_REFRESH_TOKENS': True,
    
    # Invalida los refresh tokens después de usarlos
    'BLACKLIST_AFTER_ROTATION': True,
    
    # Actualiza la última hora de inicio de sesión del usuario
    #'UPDATE_LAST_LOGIN': True,
}
#Configuracion de Swagger
SPECTACULAR_SETTINGS = {
    'TITLE': 'Barberia API',
    'DESCRIPTION': 'API REST utilizada como Backend para la plataforma Barberia.',
    'VERSION': '1.0.0',
    'CONTACT': {
        'name': 'Barberia',
        'email': 'barberia@gmail.com',
        'url': 'https://barberia.vercel.app',
    },
    #Orden de los tags en Swagger
    'TAGS': [
        {'name': 'Login', 'description': 'Operaciones de autenticación'},
        {'name': 'User', 'description': 'Operaciones relacionadas con los usuarios'},
        {'name': 'Token', 'description': 'Operaciones relacionadas con los tokens JWT'},
    ],
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
    }
}

PWA_APP_NAME = 'Barberia API'
PWA_APP_DESCRIPTION = "Barberia API"
PWA_APP_THEME_COLOR = '#0A0302'
PWA_APP_BACKGROUND_COLOR = "#1c4216"
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {'src': '/static/images/icons/icon-72x72.png', 'sizes': '72x72'},
    {'src': '/static/images/icons/icon-96x96.png', 'sizes': '96x96'},
    {'src': '/static/images/icons/icon-128x128.png', 'sizes': '128x128'},
    {'src': '/static/images/icons/icon-144x144.png', 'sizes': '144x144'},
    {'src': '/static/images/icons/icon-152x152.png', 'sizes': '152x152'},
    {'src': '/static/images/icons/icon-192x192.png', 'sizes': '192x192'},
    {'src': '/static/images/icons/icon-384x384.png', 'sizes': '384x384'},
    {'src': '/static/images/icons/icon-512x512.png', 'sizes': '512x512'},
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'es'
